name: Create Archive

on:
  release:
    types: [published]

jobs:
  build:
    name: Create Archive
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create zip file
        run: zip svs_resources assets -r pack.mcmeta -r README.md
      - name: Upload assets
        id: upload-assets
        uses: softprops/action-gh-release@v2
        with:
          files: svs_resources.zip
      - name: Put zip info to Release.txt
        run: |
          echo "\`\`\`json" >> Release.txt
          echo "{" >> Release.txt
          echo "  \"download_size\": $(stat --printf=%s svs_resources.zip)," >> Release.txt
          echo "  \"download_sha256\": \"$(sha256sum svs_resources.zip | cut -d ' ' -f 1)\"," >> Release.txt
          echo "  \"download_url\": \"${{ fromJSON(steps.upload-assets.outputs.assets)[0].browser_download_url }}\"," >> Release.txt
          echo "  \"install_size\": $([[ "$(zipinfo -t kicad-addon.zip)" =~ ^[0-9]+\ files,\ ([0-9]+)\ bytes.*$ ]]; echo ${BASH_REMATCH[1]})" >> Release.txt
          echo "}" >> Release.txt
          echo "\`\`\`" >> Release.txt
      - name: Update body of release
        uses: softprops/action-gh-release@v2
        with:
          append_body: true
          body_path: Release.txt